import { ModalityResponseDTO } from "@/backend/modules/classgroup/types/modalityTypes";
import { ClassGroupScheduleResponseDTO } from "@/backend/modules/classgroup/types/classGroupScheduleTypes";

export interface CreateClassGroupRequestDTO {
  title: string;
  capacity: number;
  description: string;
  modalityId: string; // UUID
  startDate: string; // formato ISO: "yyyy-MM-dd"
  endDate: string;   // formato ISO: "yyyy-MM-dd"
  autoGeneratedSessions: boolean;
  isEvent?: boolean; // opcional (já que no Java não tem @NotNull)
}

export interface ClassGroupResponseDTO {
  id: string; // UUID
  title: string;
  capacity: number;
  totalMembers: number;
  description: string;
  modalityDTO: ModalityResponseDTO;
  startDate: string; // formato ISO: "yyyy-MM-dd"
  endDate: string;   // formato ISO: "yyyy-MM-dd"
  nameCreator: string;
  schedulesDTO: ClassGroupScheduleResponseDTO[];
  slug: string;
}





