export enum MuscleGroup {
   CHEST = "CHEST",
   BACK = "BACK",
   SHOULDERS = "SHOULDERS",
   BICEPS = "BICEPS",
   TRICEPS = "TRICEPS",
   FOREARMS = "FOREARMS",
   QUADS = "QUADS",
   HAMSTRINGS = "HAMSTRINGS",
   GLUTES = "GLUTES",
   CALVES = "CALVES",
   ABS = "ABS",
   OBLIQUES = "OBLIQUES",
   LOWER_BACK = "LOWER_BACK",
   FULL_BODY = "FULL_BODY",
   PUSH = "PUSH",
   PULL = "PULL",
   LEGS = "LEGS",
   ARMS = "ARMS",
   CORE = "CORE",
   UPPER_BODY = "UPPER_BODY",
   LOWER_BODY = "LOWER_BODY",
}

export const MuscleGroupLabels: Record<MuscleGroup, string> = {
   [MuscleGroup.CHEST]: "Peito",
   [MuscleGroup.BACK]: "Costas",
   [MuscleGroup.SHOULDERS]: "Ombros",
   [MuscleGroup.BICEPS]: "Bíceps",
   [MuscleGroup.TRICEPS]: "Tríceps",
   [MuscleGroup.FOREARMS]: "Antebraços",
   [MuscleGroup.QUADS]: "Quadriceps",
   [MuscleGroup.HAMSTRINGS]: "Hamstrings",
   [MuscleGroup.GLUTES]: "Glúteos",
   [MuscleGroup.CALVES]: "Panturrilhas",
   [MuscleGroup.ABS]: "Abdominais",
   [MuscleGroup.OBLIQUES]: "Obliques",
   [MuscleGroup.LOWER_BACK]: "Costas Inferiores",
   [MuscleGroup.FULL_BODY]: "Corpo completo",
   [MuscleGroup.PUSH]: "Push",
   [MuscleGroup.PULL]: "Pull",
   [MuscleGroup.LEGS]: "Pernas",
   [MuscleGroup.ARMS]: "Braços",
   [MuscleGroup.CORE]: "Core",
   [MuscleGroup.UPPER_BODY]: "Parte Superior do Corpo",
   [MuscleGroup.LOWER_BODY]: "Parte Inferior do Corpo",
};
